### ISSUE TITLE
RangeError: Maximum call stack size exceeded

### ISSUE THREAD

**Issue by finfort** [lmarkus/Kraken_Example_Passport#6]
I am using _passport_ for authentication, _sequelize_ as orm, my site work well when i am logged out, and works good on some pages when i logged in, but on a few of them i got 
**RangeError: Maximum call stack size exceeded** exception when i **logged in**,
i debugged my application and saw that it lots of time enter in this function, maybe it shouldn't call every loaded file 
I am sure that there error in logic of my code, but i didn't know where

```
exports.injectUser = function (req, res, next) {
    if (req.isAuthenticated()) {
        res.locals.user = req.user;
    }
    next();
}
```

StackTrace

```
RangeError: Maximum call stack size exceeded
    at Instance.get (c:\Users\Tolik\Documents\Projects\pcs\node_modules\sequelize\lib\instance.js:178:34)
    at Model.refreshAttributes.Utils._.each.Utils._.each.funcs.(anonymous function) (c:\Users\Tolik\Documents\Projects\pcs\node_modules\sequelize\lib\model.js:749:23)
       at module.exports.sequelize.define.getterMethods.someValue (c:\Users\Tolik\Documents\Projects\pcs\models\user.js:27:16)
    at Instance.get (c:\Users\Tolik\Documents\Projects\pcs\node_modules\sequelize\lib\instance.js:186:39)
    at Model.refreshAttributes.Utils._.each.Utils._.each.funcs.(anonymous function) (c:\Users\Tolik\Documents\Projects\pcs\node_modules\sequelize\lib\model.js:749:23)
    at module.exports.sequelize.define.getterMethods.someValue (c:\Users\Tolik\Documents\Projects\pcs\models\user.js:27:16)
    at Instance.get (c:\Users\Tolik\Documents\Projects\pcs\node_modules\sequelize\lib\instance.js:186:39)
    at Model.refreshAttributes.Utils._.each.Utils._.each.funcs.(anonymous function) (c:\Users\Tolik\Documents\Projects\pcs\node_modules\sequelize\lib\model.js:749:23)
    at module.exports.sequelize.define.getterMethods.someValue (c:\Users\Tolik\Documents\Projects\pcs\models\user.js:27:16)
    at Instance.get (c:\Users\Tolik\Documents\Projects\pcs\node_modules\sequelize\lib\instance.js:186:39)
    at Model.refreshAttributes.Utils._.each.Utils._.each.funcs.(anonymous function) (c:\Users\Tolik\Documents\Projects\pcs\node_modules\sequelize\lib\model.js:749:23)
    at module.exports.sequelize.define.getterMethods.someValue (c:\Users\Tolik\Documents\Projects\pcs\models\user.js:27:16)
    at Instance.get (c:\Users\Tolik\Documents\Projects\pcs\node_modules\sequelize\lib\instance.js:186:39)
    at Model.refreshAttributes.Utils._.each.Utils._.each.funcs.(anonymous function) (c:\Users\Tolik\Documents\Projects\pcs\node_modules\sequelize\lib\model.js:749:23)
    at module.exports.sequelize.define.getterMethods.someValue (c:\Users\Tolik\Documents\Projects\pcs\models\user.js:27:16)
    at Instance.get (c:\Users\Tolik\Documents\Projects\pcs\node_modules\sequelize\lib\instance.js:186:39)
```

i am using this for configuration 

```
app.use(passport.initialize());
app.use(passport.session()); 
app.use(flash());
app.use(auth.injectUser);
```

controllers/login/index.js

```
router.get('/', function(req, res) {
        res.render('login', { message: req.flash('loginMessage') });
    });


router.post('/', passport.authenticate('local-login', {
        successRedirect : '/profile', 
        failureRedirect : '/login', 
        failureFlash : true 
    }));
```

passport.js

```
 passport.serializeUser(function(user, done) {
        done(null, user.id);
    });

    // used to deserialize the user
    passport.deserializeUser(function(id, done) {
        User.findById(id).then(function(user){
            done(null, user); // it gets here on every loaded file after injectUser
        }).catch(function(e){
            done(e, false);
        });
    });
```

package.json

```
"express": "^4.13.3",
"express-session": "^1.11.3",
"passport": "^0.3.2",
"passport-local": "^1.0.0",
"kraken-js": "^1.0.3",
"sequelize": "^3.11.0",
"pg": "^4.4.2"
```

**Comment by finfort** [comment]
Found solution it was connected with passport.deserializeUser method and proper app configuration 
app.use(express.static(__dirname + '/public', { maxAge: oneDay }));
http://stackoverflow.com/a/34567069/880709

**Comment by lmarkus** [comment]
I love self-solving problems :)
